// Built-in pack of real, natural sentences. Picked at random at runtime.
const SENTENCES = [
  "The morning light slipped quietly through the kitchen window.",
  "She poured another cup of tea and watched the rain fall.",
  "A good book and a warm blanket make any evening better.",
  "The old wooden floor creaked softly under his bare feet.",
  "Somewhere down the street a dog barked at the passing train.",
  "We talked for hours about everything and nothing at all.",
  "The bakery smelled of cinnamon long before it opened.",
  "He folded the letter carefully and slipped it into his pocket.",
  "Autumn leaves drifted across the empty playground.",
  "The cat curled into a tight ball on the sunlit chair.",
  "Snow began to fall just as the lamps flickered on.",
  "Her grandmother always said patience was its own reward.",
  "The garden was quiet except for the hum of bees.",
  "They watched the last train leave without saying a word.",
  "A single candle lit the corner of the crowded room.",
  "The coffee had gone cold but he kept drinking it anyway.",
  "Waves rolled gently against the worn stone harbor.",
  "She hummed an old song while kneading the bread.",
  "The map was creased and faded but still good enough.",
  "Fireflies blinked across the meadow as dusk settled in.",
  "He learned to whistle the tune his father used to play.",
  "The library was silent save for the turning of pages.",
  "Rain tapped a steady rhythm on the tin roof above.",
  "We shared an umbrella and laughed at the puddles.",
  "The kettle whistled just as the storm broke outside.",
  "A warm loaf of bread sat cooling on the counter.",
  "The stars seemed brighter far away from the city lights.",
  "She wrapped the gift in plain brown paper and string.",
  "The path wound gently through the misty morning fields.",
  "He always kept a spare pencil tucked behind his ear.",
  "The clock on the wall had stopped at half past three.",
  "They roasted marshmallows until the fire burned low.",
  "Soft music drifted from the open window next door.",
  "The puppy chased its tail in dizzy little circles.",
  "She pressed wildflowers between the pages of her diary.",
  "The train rattled past fields of golden wheat.",
  "He sketched the harbor while the gulls wheeled overhead.",
  "A gentle breeze carried the scent of fresh cut grass.",
  "The children built a fort out of every cushion they could find.",
  "We counted the stars until we both fell asleep.",
  "The shop bell jingled each time the door swung open.",
  "Morning fog hung low over the sleepy little village.",
  "She knitted a scarf the color of late autumn leaves.",
  "The river moved slow and silver beneath the bridge.",
  "He read the same paragraph three times before giving up.",
  "The orchard was heavy with apples ready to be picked.",
  "They danced in the kitchen long after the music ended.",
  "A thin ribbon of smoke rose from the chimney.",
  "The lighthouse blinked patiently across the dark water.",
  "She saved the crossword for the quiet part of the afternoon.",
  "Warm bread and cold butter is a simple kind of joy.",
  "The trail was muddy but the view was worth every step.",
  "He whittled a small boat from a piece of driftwood.",
  "The market buzzed with the chatter of early shoppers.",
  "Snowflakes melted the moment they touched her glove.",
  "The porch swing creaked gently in the evening wind.",
  "We followed the sound of music to the little square.",
  "A stack of records leaned against the dusty turntable.",
  "The soup simmered slowly while the snow piled higher.",
  "She tucked a note inside the book before returning it.",
  "The old dog stretched and yawned in the patch of sun.",
  "Lanterns swayed above the narrow cobblestone street.",
  "He saved the best chair by the window for himself.",
  "The valley filled with mist as the sun went down.",
  "They planted tomatoes along the sunny side of the fence.",
  "A worn quilt covered the foot of the narrow bed.",
  "The first frost laced the windows with delicate patterns.",
  "She always knew exactly which key opened which door.",
  "The campfire crackled and sent sparks into the dark.",
  "He kept every postcard he had ever received.",
  "The hills turned gold in the slow light of evening.",
  "We picked blackberries until our fingers were stained purple.",
  "The radio played softly through the quiet afternoon.",
  "A row of boots stood drying by the back door.",
  "The cabin smelled of pine and woodsmoke and rain.",
  "She traced the rim of her mug while she thought.",
  "The ferry crossed the bay just as the sky turned pink.",
  "He hummed to himself as he swept the front steps.",
  "The meadow was loud with crickets after dark.",
  "They left the porch light on for whoever came home last.",
  "A soft rain made the whole town smell like spring.",
  "The bookshop cat slept in the window every afternoon.",
  "She wrote letters she never quite got around to sending.",
  "The bridge was lined with little locks and faded ribbons.",
  "He kept his change in an old chipped teacup.",
  "The bakery sold out of rolls before nine every morning.",
  "We watched the tide come in and erase our footprints.",
  "The attic was full of boxes nobody dared to open.",
  "She left fresh flowers on the table every Sunday.",
  "The wind chimes sang in the cool of the morning.",
  "He could fix almost anything with patience and tape.",
  "The path home was longer but far more beautiful.",
  "A pot of stew bubbled away on the back burner.",
  "They told stories until the candles guttered out.",
  "The first cup of coffee is always the best one.",
  "She hung the laundry to dry between the apple trees.",
  "The snow muffled every sound in the little town.",
  "He found an old photograph tucked inside the frame.",
  "The garden gate squeaked a friendly sort of welcome.",
  "We shared a slice of pie and two clean forks.",
  "The harbor lights reflected in the still black water.",
  "She always read the last page first, just to be safe.",
  "The fire threw dancing shadows across the low ceiling.",
  "He carried the groceries up three flights without complaint.",
  "The afternoon stretched long and warm and unhurried.",
  "A single sparrow hopped along the frosty railing.",
  "They watched old films until the sun came up.",
  "The kettle was the first thing she reached for each day.",
  "He folded the map wrong and we laughed the whole way.",
  "The orchard hummed with the sound of summer afternoons.",
  "She wore her father's old sweater all through winter.",
  "The lake was a perfect mirror in the early calm.",
  "We left the window open to listen to the storm.",
  "The little cafe kept one table just for regulars.",
  "He saved string and buttons in a battered tin box.",
  "The trail ended at a quiet, sunlit clearing.",
  "She baked an extra loaf to leave on a neighbor's step.",
  "The moon rose huge and orange over the rooftops.",
  "They spent the whole rainy day building a blanket fort.",
  "A warm light glowed in the window all through the night.",
  "The old clock ticked a slow and steady comfort.",
  "He whistled the same three notes whenever he was happy.",
  "The first snow always made the whole world feel new."
];
